### PR TITLE
Grammatical correction of some comments

### PR DESCRIPTION
**Pull request by mokarchi**

### CODE REVIEW

**Comment by martincostello** [comment]
@mokarchi If you rebase on to the default branch to pick up our new CI and revert the namespace changes I can merge this for you.

**Review by martincostello — COMMENTED** [review]
Please revert the namespace sorting changes.

**Comment by mokarchi** [comment]
> Please revert the namespace sorting changes.

I can't manipulate the order and it will be sorted automatically by saving the file

**Comment by martincostello** [comment]
Then use another editor or the GitHub UI which won't do that 😄

**Review by martincostello — APPROVED** [review]
Thanks!

**Pull request merged**
