### PR TITLE
Fix OpenAPI flow

### LINKED ISSUE #1241: Available Authorizations modal is empty with v5 OpenIdConnect configuration
Running .Net Core 2.2 and Swashbuckle.AspNetCore 5.0.0-rc2.

Trying to setup OIDC configuration, but the Available Authorizations modal is blank, so cannot proceed with authentication.

Configuration as follows:

```csharp
services.AddSwaggerGen(c => {
...
c.AddSecurityDefinition("token", new OpenApiSecurityScheme {
    Type = SecuritySchemeType.OpenIdConnect,
    OpenIdConnectUrl = new Uri($"https://login.microsoftonline.com/{tenant}/v2.0/.well-known-openid-configuration")
});
c.AddSecurityRequirement(new OpenApiSecurityRequirement {
    {
        new OpenApiSecurityScheme {
            Reference = new OpenApiReference {Type = ReferenceType.SecurityScheme, Id = "token"
        }, new string[] { }
    }
});
...
});

services.UseSwaggerUI(c => {
...
c.OAuthClientId(_clientId);
...
});

### PR DESCRIPTION
**Pull request by IhnatKlimchuk**
Update for [Issue 1241](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1241) to support OpenAPI. Fixes #1241

as @hkosova mentioned:
```
OpenID Connect Discovery is now supported in Swagger UI v. 3.38.0.
```
We now can add Open API support, but unfortunately during testing with new sample project I have found out that [swagger-ui](https://github.com/swagger-api/swagger-ui) repository contains bug described in [Issue 6741](https://github.com/swagger-api/swagger-ui/issues/6741) that prevents from full flow testing. 

Going to create a PR in `swagger-ui` soon. @hkosova can you please help me with [Issue 6741](https://github.com/swagger-api/swagger-ui/issues/6741) review?

### CODE REVIEW

**Comment by domaindrivendev** [comment]
As the only change to Swashbuckle is pulling in the latest version of the swagger-ui, I don't think the test project is neccessary - i.e. it's not Swashbuckle's responsbility to test the swagger-ui code. If you remove the test project I'll accept the swagger-ui update to `3.38.0`

**Comment by Rutix** [comment]
@domaindrivendev as far as I can see you updated to 3.39.0 in the following commit https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/5652e8121f982a628563b0d324147096d40c1c6b

This one can probably be closed then too :)

**Comment by IhnatKlimchuk** [comment]
Swagger was released https://github.com/swagger-api/swagger-ui/releases/tag/v3.40.0 with fix for issue https://github.com/swagger-api/swagger-ui/issues/6741 that was resolved by https://github.com/swagger-api/swagger-ui/pull/6750, going to update PR soon.

**Comment by IhnatKlimchuk** [comment]
@domaindrivendev @Rutix you can either update swagger-ui to 3.40 in separate PR or merge this, as I have removed sample project for OpenAPI usage

**Pull request merged**
