### PR TITLE
Update README.md - Fix `Add Security Definitions and Requirements for Bearer auth` URL

### PR DESCRIPTION
**Pull request by Saibamen**
Fix `Add Security Definitions and Requirements for Bearer auth` URL

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements-for-bearer-auth

### CODE REVIEW

**Review by 304NotModified — APPROVED** [review]
Tested and LGTM!

**Comment by 304NotModified** [comment]
PS dupl of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2591

**Comment by martincostello** [comment]
Thanks for contributing - if you'd like to continue with this pull request, please rebase against the default branch to pick up our new CI. Whoever does it first between this PR and #2591 wins 😄.

**Comment by Saibamen** [comment]
Done

**Review by martincostello — APPROVED** [review]

**Pull request merged**
