### PR TITLE
Consistent dependency injection of SwaggerOptions and SwaggerUIOption…

### PR DESCRIPTION
**Pull request by nuttytree**
…s when using a setup action on the UseSwagger and UseSwaggerUI methods.

### CODE REVIEW

**Comment by nuttytree** [comment]
This PR resolves issue #1829

**Comment by domaindrivendev** [comment]
@nuttytree - we need to revisit this PR. While it introduces some additional consistency, it removes the flexability to configure multiple instances of the middleware with different configurations. For example, the following configuration to emit v2 and v3 versions of the Swagger/OpenAPI JSON side by side is now broken:

```csharp
app.UseSwagger(c =>
{
    c.RouteTemplate = "swagger/{documentName}/swagger.json";
    c.SerializeAsV2 = true;
});

app.UseSwagger(c =>
{
    c.RouteTemplate = "/swagger/{documentName}/openapi.json";
});
```

**Comment by nuttytree** [comment]
I just got done with really rough day at work trying to track down a very problematic bug.  I will take a look tomorrow and see if I can come up with a solution.

**Comment by domaindrivendev** [comment]
@nuttytree no worries - I went ahead and pushed the following change - b6c6919c8fc19394f767d6159bb6286036e2e843, which feels like a decent compromise. Basically, if you use the overload that accepts a setup action `Action<SwaggerOptions>` then your using the DI-injected options. Alternatively, if you want to configure multiple instances of the middleware with independent options, then you use the overload that accepts a `SwaggerOptions` instance.

**Pull request merged**
