### PR TITLE
Configure a default SwaggerDoc if none provided

### PR DESCRIPTION
**Pull request by domaindrivendev**
If a `SwaggerDoc` has not been provided in `Startup.cs`, use a default with `Title = _webHostEnvironment.ApplicationName, Version = "1.0"`.

This supports a simplified config. E.g:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddSwaggerGen();
    ...
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    ...
    services.AddSwagger();
    ...
}
```

### CODE REVIEW

**Comment by domaindrivendev** [comment]
@rynowak, @bradygaster

**Comment by bradygaster** [comment]
@domaindrivendev sweet! thanks for the update.

**Comment by bradygaster** [comment]
Also - we discussed making the middleware a little easier for dialing in a custom server/host name. Is that something you're planning on adding in this update or a latter one? 

Thanks again. Looking forward to this.

**Comment by domaindrivendev** [comment]
> Also - we discussed making the middleware a little easier for dialing in a custom server/host name. Is that something you're planning on adding in this update or a latter one?

@bradygaster - I'll do this as a separate commit/PR. I created issue #1634 to capture the details. Would yo mind posting your `IDocumentFilter` implementation to that issue thread to ensure I capture the requirements correctly.

**Pull request merged**
