### PR TITLE
Update to .netstandard 2.0

### PR DESCRIPTION
**Pull request by kimiko88**
Fix error using netcore 2.0

### CODE REVIEW

**Comment by tillig** [comment]
Duplicate of #464.

See #464 for an explanation of why Swashbuckle intentionally has not upgraded to netstandard 2.0. This PR will likely not be accepted.

**Comment by kimiko88** [comment]
Sorry, I didn't see #464. 

I upgrade to netstandard 2.0 for the same reason of @JanEggers in #464.

I understand your explanation but if someone want to use Swashbuckle in a netcore 2.0 project, need an upgrade like this.

**Comment by tillig** [comment]
No, see #468. You can use it in netcore 2 projects without the upgrade. Just add the reference to the static files assembly. This is going to be a common sort of thing in netstandard / netcore - new to .NET people but something folks who use things like Node (lots of transitive dependencies) are used to.

**Comment by kant2002** [comment]
I think this version should not replace support for .netstandard 1.6, but instead of add libraries required for .NET Standard 2.0 and use `#ifdef` to provide support for both versions. That way minimal version still would be the same, but at the same time support would be preserved.

**Comment by tillig** [comment]
I'm not sure there's a lot of value in that. The problem is that this sort of thing pops up when almost any transient dependency gets an update or any new netstandard version gets released. If the "fix" for the problem is to add a direct reference to `Microsoft.AspNetCore.StaticFiles`, that seems easy enough. That's also the official Microsoft solution for any sort of security upgrades they issue - add direct references to the upgraded packages right to your project.

Targeting netstandard 1.6 means it does work with netstandard 2.0. The larger issue is the MVC dependencies, specifically the StaticFiles dependency, right? It's not different code that needs to execute in Swashbuckle.

Again, this is stuff folks who use systems with large numbers of small and transient dependencies are kind of used to. It's a new and unfamiliar pain to .NET folks, but it's the trade-off for having netstandard/netcore.

Anyway, it's up to @domaindrivendev if he wants to maintain that. I'm just saying, this is a solved problem and it doesn't make sense to add support burden at this level.

**Comment by kant2002** [comment]
@tillig Sorry, I probably don't understand from discussion in both issues that all that should be done is just explicitly require `Microsoft.AspNetCore.StaticFiles` which is more then fine for me.

**Comment by adamhathcock** [comment]
Is this being looked at?  Using on a ASP.NET Core 2 project pulls in 1.0 dependencies.

**Comment by quetzalcoatl** [comment]
FYI: for asp-core 2.1 the fix of "just link static-files" does not seem to work anymore. See #438

**Comment by MedAnd** [comment]
Same issue as others, all static files return **500 Internal Server Error** from Kestrel... any recommended workaround?

- Swashbuckle.AspNetCore Version 3.0.0 
- Microsoft.AspNetCore.Server.Kestrel Version 2.1.1
- Microsoft.AspNetCore.StaticFiles Version 2.1.1
- .Net Core 2.1.302 
- Ubuntu 16.04

**Comment by domaindrivendev** [comment]
Upgrade min bound to netstandard2.0 was already merged in #806. Will be available with the next major release - 4.0.0, coming soon.

**Comment by MedAnd** [comment]
Thanks for the follow-up @domaindrivendev .... any ETA?

**Pull request closed without merging**
