### PR TITLE
Move to preview7 version of Microsoft.Extensions.ApiDescription.Server package

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
Thanks @domaindrivendev❕

Any update on the next release? And will that be 5.0.0-rc3 or 5.0.0?

**Comment by domaindrivendev** [comment]
TBH I’m pretty far behind on tackling several show-stopping issues that were introduced with the OA3 refactor. I’m in the middle of another size-able refactor that should resolve a number of these in one go but just haven’t been able to find the contiguous time to complete that.

I’m gonna have some free time mid aug and intend to tie up the critical issues then. Once that’s done, I’ll likely put out an rc3 version for a week or so (some crowd sourced ad-how testing would be much appreciated at that time) and if all is good then get the stable version out ... finally

**Comment by dougbu** [comment]
Thanks for the info @domaindrivendev

**Pull request merged**
