### PR TITLE
Added SwaggerUI 3 project

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
This pull request based on this one: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/453 with the request from @domaindrivendev

So I kept both SwaggerUI 2 and Swagger UI 3 in one solution and it is possible to use it like this
```C#
app.UseSwaggerUI3(c =>
{
    ...
});
```

I've used swagger-ui 3.5.0
Fixed: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/466, https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/515

### CODE REVIEW

**Comment by JosKrause** [comment]
As a suggestion and as long as this PR has not been merged yet, perhaps we could update it to match the latest release of SwaggerUI? 

At the time of writing: **v3.6.1**

**Comment by alexvaluyskiy** [comment]
@JosKrause done

**Comment by domaindrivendev** [comment]
So ... I did merge your commits, but also added additional changes on top to apply newer patterns for the embedded UI. Unfortunately, I somehow detached those changes from this PR. For your reference here's the 3 commits to master in question:

Your first commit: 098ef405882799877110e0b02d6ee7d8af59af37
Your second commit: 4856f13d1278e8266f3673b41e2f8d216b44e99b
My commit: 098ef405882799877110e0b02d6ee7d8af59af37

Thanks for the contribution and apologies for screwing up the PR workflow :(

**Comment by josephearl** [comment]
Please can we have a new release with this included? Thanks

**Comment by domaindrivendev** [comment]
It's a available as a preview package on myget: https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore.SwaggerUI3

**Comment by divinebovine** [comment]
@domaindrivendev I see that you had a preview package back in Jan 2018, but it doesn't look like this code (including your commit) was merged into master. At least I can't find it and the `UseSwaggerUI3` extension method is not available as of 5.0.0-rc2. Is there any update to this that you can provide?

**Pull request closed without merging**
