### PR TITLE
Azure Functions support

### PR DESCRIPTION
**Pull request by xDDDx**
Hi, 

in the current project we use ASP.NET Core 2.0 Web Api for SPA and Azure Functions for background and data synchronisation processing. 

For CD we need dynamicly generated swagger.json for our functions, but I didn't found anything. So I decided to try to adapt your great project for Azure Functions support.

These are the results after one week of work and it's working great for us. 

I'm sure, there are not all aspects of Azure Functions implemented, but for our purpose it's enough and is just the first step.

It will be great to get full Azure Functions support from you guys someday and I hope it will help you.

The keys are, it should be .NETStandard2.0 library. It wasn't possible for me to get it compiled or running without upgrade to it. That's why I choosed .netstandard2.0 branch to work on.

Thanks
Dima

### CODE REVIEW

**Comment by cal5barton** [comment]
Any updates on whether Azure Functions will be supported in the future?

**Comment by bherila** [comment]
Would be great to have a first step available and working/tested! How can we move forward with this?

**Comment by domaindrivendev** [comment]
see #913

**Comment by bherila** [comment]
For anyone who finds this issue, here is the answer: https://www.nuget.org/packages/Swashbuckle.AspNetCore.AzureFunctions/

**Pull request closed without merging**
