### PR TITLE
Add support for <ineritdoc cref="" />

### PR DESCRIPTION
**Pull request by codecooper**
In answer to [Issue #2597](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2597), this will recursively scan the XML documentation to gather the first property/attribute that contains the needed value. This change would work automatically without the user having to do anything extra.

### CODE REVIEW

**Comment by soroshsabz** [comment]
ITNOA

I need this feature too

**Comment by soroshsabz** [comment]
@codecooper  please request this PR to https://github.com/Havunen/DotSwashbuckle

**Comment by martincostello** [comment]
Thanks for contributing - if you'd like to continue with this pull request, please rebase against the default branch to pick up our new CI.

**Comment by soroshsabz** [comment]
@codecooper Do you have any time to rebase this PR?

**Comment by soroshsabz** [comment]
@martincostello What is policy to How much waiting for PR owner to make PR ready for merging? in another word when we can create another PR for this feature?

**Comment by codecooper** [comment]
I have just started on the rebase. It should be done this week as time permits.

**Comment by soroshsabz** [comment]
@martincostello please reopen PR

thanks

**Comment by martincostello** [comment]
Even if I re-open it, it still needs rebasing. If the original contributor wishes to come back to this work, then can do so as a new PR.

**Comment by soroshsabz** [comment]
Finally, PR #3016 replaces this PR

thanks @codecooper

**Pull request closed without merging**
