### PR TITLE
Update CLI project to target net5.0 in addition to netcoreapp3.0 and netcoreapp2.1

### PR DESCRIPTION
**Pull request by ctyar**

### CODE REVIEW

**Comment by Shkarface** [comment]
When will this be merged? we cannot update our apps to .net 5.0 because the cli is part of our CI system

**Comment by mikeblakeuk** [comment]
Please also update all the Nuget packages as per # #1906

**Comment by mikeblakeuk** [comment]
Should we also use .net 3.1
The target framework 'netcoreapp3.0' is out of support and will not receive security updates

**Comment by mikeblakeuk** [comment]
> When will this be merged? we cannot update our apps to .net 5.0 because the cli is part of our CI system

It will support both 5.0 and 3.x

**Comment by iSeiryu** [comment]
Same as @Shkarface. Right now we are forced to install both 3.1 and 5.0 on our CI servers to do the build and then to run swagger cli.

**Comment by atrauzzi** [comment]
Any chance this can be merged and released?  Currently unable to install in a `net5.0` project.

**Comment by vcaraulean** [comment]
We got a workaround in place, it might not suit everyone but the idea, in general lines is following:
 - have swagger integration in the main app
 - create an integration test to grab the `swagger.json` from your app-under-test (`TestServer`)
 - dump it to a file in a location that following CI steps can grab it.

Using [Alba](https://jasperfx.github.io/alba/) testing framework it looks like this:

```csharp
        [Fact]
        public async Task WriteSwaggerFileToDisk()
        {
            var result = await system.Scenario(x =>
            {
                x.Get.Url("/swagger/v1/swagger.json");
                x.StatusCodeShouldBeOk();
            });

            await File.WriteAllTextAsync("../../../../swagger.json", result.ResponseBody.ReadAsText());
        }
```

**Comment by fabich** [comment]
@domaindrivendev any chance you can merge this?

**Comment by mikeblakeuk** [comment]
warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future.

**Comment by philBrown** [comment]
Any idea on when this will make it into a release?

**Comment by ZOFLLUTZ** [comment]
@domaindrivendev are there any plans on when there will be a release with the support of .Net 5?

**Pull request merged**
