### PR TITLE
Add additional verify tests

### PR DESCRIPTION
**Pull request by keahpeters**
Resolves: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2811

This PR introduces equivalent snapshot tests for the majority of the unit tests in `SwaggerGeneratorTests`. 

- Added snapshot tests that mirror most of the existing unit tests in SwaggerGeneratorTests.
- Unit tests that focus on specific conditions or exceptions being thrown are not duplicated as snapshot tests.
- Snapshot tests complement the existing unit tests and ensure generated Swagger documents are as expected.

### CODE REVIEW

**Review by martincostello — APPROVED** [review]
Awesome work!

**Comment by martincostello** [comment]
Looks like we're hitting MAX_PATH issues with the Windows build though: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/actions/runs/9537731930/job/26287650221?pr=2950#step:2:61

**Comment by mesMess** [comment]
Just pulled this from fresh and the path limit is still an issue.
No issues on Mac or Linux.
Was this tested after resolution?

> error: unable to create file test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests/SwaggerGeneratorVerifyTests.IllegalHeaderParameterWithOpenApiOperation_action=ActionWithAuthorizationFromHeaderParameter.verified.txt: Filename too long
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.

**Comment by martincostello** [comment]
It was tested in so far as the CI no longer had the issue after changes were made, and other people have made contributions without issue.

How long is the path you're cloning the repo into?

**Comment by mesMess** [comment]
On Windows, 261 (default limit is 260) characters.
On Unix and Linux, no problems.
I can shorten the base directory on Windows (or mod the registry) was just curious. In either case the name of that file is too long for no reason.

**Pull request merged**
