### PR TITLE
Fix broken link in README.md

### PR DESCRIPTION
**Pull request by matiand**

### CODE REVIEW

**Review by 304NotModified — APPROVED** [review]
Tested and LGTM

**Comment by 304NotModified** [comment]
PS, same fix is also submitted here: #2705

**Comment by martincostello** [comment]
Thanks for contributing - if you'd like to continue with this pull request, please rebase against the default branch to pick up our new CI. Whoever does it first between this PR and #2705 wins 😄.

**Comment by martincostello** [comment]
Fixed by #2705.

**Pull request closed without merging**
