### PR TITLE
Added support for custom WebHostBuilder when using cli

### PR DESCRIPTION
**Pull request by tburi**
This enables the CLI tool to run on projects with custom webhost configurations.
ex. adding autofac, custom config files etc.

Added an example project with autofac. CliExampleWithFactory

### CODE REVIEW

**Comment by kipmaplewave** [comment]
This PR is also important for current projects we are working on.  We have a similar patch, but obviously don't want to maintain a fork.  Is their an ETA when this will be added to master?

**Comment by officeSpacePirate** [comment]
@domaindrivendev Is this PR a direction you're good to go with? If so and @tburi doesn't have the time, I would be willing to resolve the conflicts in a new PR. Equivalent support is blocking my team from using the CLI tool.

**Comment by brooknovak** [comment]
Why is this not being merged? 
We were using this nice CLI tool, but its now breaking due to our projects now using the webhost builder configure method for a custom service provider (in our case we are using castle windsor).

**Comment by michalsteyn** [comment]
Would also love this feature

**Comment by domaindrivendev** [comment]
Merged with some minor code cleanup

**Pull request merged**
