### PR TITLE
ASP.NET Core 3.0 support ---- StaticFileMiddleware

### PR DESCRIPTION
**Pull request by pengweiqhca**
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1061

### CODE REVIEW

**Comment by JohnGalt1717** [comment]
Any chance we can get this prioritized because Even with V5.rc1 UI won't work until this is fixed.

See comment on: #1061


Thanks!

**Comment by domaindrivendev** [comment]
On it ...

**Comment by domaindrivendev** [comment]
@JohnGalt1717 any chance you could pull and verify the v5.0.0-rc2 preview from myget.org as I don't want to pollute the official feed with bad versions?

**Comment by JohnGalt1717** [comment]
@domaindrivendev  I was just about to post this:

Before posting this for another RC, using a C# httpclient and doing a GetStringAsync() to the right URI that comes up in the browser causes an exception from httpclient:

System.IO.IOException: 'The server returned an invalid or unrecognized response.'


Again, works fine in postman and chrome but blows up in httpclient. 

Here's the error dumped to the logs of the site:

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetChunkedMemory(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetSpan(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.GetSpan(Int32 sizeHint)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteMultiSegmentEncoded(PipeWriter writer, String text, Encoding encoding, Span`1 destination, Int32 encodedLength)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.RespondWithSwaggerJson(HttpResponse response, OpenApiDocument swagger)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

**Comment by martincostello** [comment]
Maybe that’s a bug in 3.0 itself? Happy to try it myself from MyGet tomorrow as well if it helps out.

**Comment by JohnGalt1717** [comment]
I can request any other webapi page from httpclient. It's only swashbuckler's json that fails.

**Comment by martincostello** [comment]
I haven't ported the changes to my 3.0.0-preview3 branch yet, but using `5.0.0-rc1` works fine serving the JSON document with 2.2 in my project PR to update to 5, which includes an integration test for fetching it: https://github.com/martincostello/alexa-london-travel-site/pull/260

**Comment by martincostello** [comment]
Serving the JSON document is also fine in my ASP.NET Core 3.0 PR https://github.com/martincostello/alexa-london-travel-site/pull/255.

**Comment by domaindrivendev** [comment]
> Before posting this for another RC, using a C# httpclient and doing a GetStringAsync() to the right URI that comes up in the browser causes an exception from httpclient:

@JohnGalt1717 - I just put together the following test and the JSON is outputted without issue. So, no repro for me:

```csharppublic class Spike
{
    private readonly ITestOutputHelper _output;

    public Spike(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    public async Task Test()
    {
        var client = new HttpClient();

        var json = await client.GetStringAsync("http://localhost:14670/swagger/v1/swagger.json");

        _output.WriteLine(json);
    }
}
```

**Comment by martincostello** [comment]
No issues for me with RC2 either.

**Comment by JohnGalt1717** [comment]
@domaindrivendev I'm away this weekend. I'll repro Monday.

**Comment by lborba** [comment]
> No issues for me with RC2 either.
Using RC2 here and I am facing the same issue that @JohnGalt1717 mentioned earlier, the swagger.json is not sent properly. But it only happens when running from a docker container (and also after deploying to a k8s cluster), when running directly from VS2019 it works.

**Comment by JohnGalt1717** [comment]
RC2 is still having issues.  The only thing I can think of is that might be different is that I'm using versioning.

Here's the error: 

`Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Memory`1.Slice(Int32 start, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetChunkedMemory(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetSpan(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.GetSpan(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.GetSpan(Int32 sizeHint)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteMultiSegmentEncoded(PipeWriter writer, String text, Encoding encoding, Span`1 destination, Int32 encodedLength)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.RespondWithSwaggerJson(HttpResponse response, OpenApiDocument swagger)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)`

Here's my config:

```
services.AddSwaggerGen(options =>
{
var provider = serviceProvider.GetRequiredService<IApiVersionDescriptionProvider>();
}

				foreach (var description in provider.ApiVersionDescriptions)
				{
					options.SwaggerDoc(
						description.GroupName,
						new OpenApiInfo
						{
							Title = $"Nexus API {description.ApiVersion}",
							Version = description.ApiVersion.ToString(),
							TermsOfService = new Uri("https://www.4dnexus.com/terms"),
							Description = "Complete API Documentation."
						});
				}

```

and finally

```
			app.UseSwagger(options =>
			{
				options.RouteTemplate = "help/{documentName}/swagger.json";
				
			});

```

**Comment by JohnGalt1717** [comment]
And Rc2 is still failing with Swagger UI.

**Comment by martincostello** [comment]
Possibly looks like a bug in 3.0.0-preview3?

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. at System.Memory1.Slice(Int32 start, Int32 length)
```

Looks like something in Kestrel is bugging out trying to write the JSON to the HTTP stream.

**Comment by JohnGalt1717** [comment]
@martincostello  why does it work in Postman but not Fiddler?

**Comment by martincostello** [comment]
HTTPS vs. HTTP? Different request headers being sent?

**Comment by JohnGalt1717** [comment]
Exactly the same URL: https://localhost:44351/help/v1/swagger.json

Fails in Fiddler and with httpclient and works with postman.

**Comment by martincostello** [comment]
Is Postman sending different request headers than the other two? Without having access to your application to debug it's difficult to guess as to what might be going wrong.

The exception is coming from here, which at first glance seems fine to me:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f85d3e663caeda076d81adfde5e5ad90102d1fd/src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs#L86-L92

Either there's a intermittent bug in this code is trying to write out the JSON that's been there since f23d36a94c0384c6fa120f972755c36c980eb2fb was merged, or there's a bug in 3.0.0-preview3 inside ASP.NET Core itself that's causing the requests in your application to fail.

Whatever's causing this bug seems specific to _something_ in your application though, as I've updated two completely different and unrelated applications to 5.0.0-rc2 now and neither have had exhibited this problem.

**Comment by JohnGalt1717** [comment]
I've disabled everything I can find with no joy. I've gone the reverse and started adding stuff incrementally and added everything and no joy.

**Comment by dongshengfengniaowu** [comment]
":"Type: System.ArgumentOutOfRangeException\r\nMessage: Specified argument was out of the range of valid values.\r\nDataJson: {}\r\nStacktrace:\r\n   at System.Memory`1.Slice(Int32 start, Int32 length)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetChunkedMemory(Int32 sizeHint)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetSpan(Int32 sizeHint)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.GetSpan(Int32 sizeHint)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.GetSpan(Int32 sizeHint)\r\n   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteMultiSegmentEncoded(PipeWriter writer, String text, Encoding encoding, Span`1 destination, Int32 encodedLength)\r\n   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)\r\n   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.RespondWithIndexHtml(HttpResponse response)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

**Comment by martincostello** [comment]
@pranavkm @rynowak @glennc Do any of you have any insight to the above exceptions that @JohnGalt1717 and @dongshengfengniaowu are observing?

**Comment by martincostello** [comment]
Actually, I am replicating this now in the integration tests for an application updated to 5.0.0-rc2 with 3.0.0-preview3:

## Server logs

```
[19:07:18][Step 7/17] fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
[19:07:18][Step 7/17]       An unhandled exception has occurred while executing the request.
[19:07:18][Step 7/17] System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
[19:07:18][Step 7/17]    at System.Memory`1.Slice(Int32 start, Int32 length)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetChunkedMemory(Int32 sizeHint)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetSpan(Int32 sizeHint)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.GetSpan(Int32 sizeHint)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.GetSpan(Int32 sizeHint)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteMultiSegmentEncoded(PipeWriter writer, String text, Encoding encoding, Span`1 destination, Int32 encodedLength)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
[19:07:18][Step 7/17]    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.RespondWithSwaggerJson(HttpResponse response, OpenApiDocument swagger)
[19:07:18][Step 7/17]    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
[19:07:18][Step 7/17]    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

## Test logs

```
System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MyApp.Swagger.SwaggerTests.Can_Load_Swagger_Documentation(String requestUri, String userAgent) in C:\BuildAgent\work\2bda9dae9152226c\tests\MyApp.EndToEndTests\Swagger\SwaggerTests.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
```

**Comment by pranavkm** [comment]
@tratcher \ @jkotalik might be able to help with this.

**Comment by jkotalik** [comment]
Yeah seems like a bug in our new pipe work in Kestrel. This is what is throwing: https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http/Http1OutputProducer.cs#L568. I think I see the issue.

**Comment by Tratcher** [comment]
This is being tracked by https://github.com/aspnet/AspNetCore/issues/8815.

**Comment by martincostello** [comment]
Thanks everyone.

**Comment by dongshengfengniaowu** [comment]
Anything update?

**Comment by martincostello** [comment]
This will be fixed in preview 4 of ASP.NET Core 3.0.0.

**Comment by endeffects** [comment]
This is still not fixed on the current Preview 4 und 5 Builds.

**Comment by pranavkm** [comment]
@endeffects could you file an issue in https://github.com/aspnet/AspNetCore/issues if you're still seeing this with the Preview4 release?

**Pull request merged**
