### PR TITLE
Modified SchemaRegistry to honor EnumMember attributes

### PR DESCRIPTION
**Pull request by rboada04**
Modified SchemaRegistry to honor EnumMember attribute values (as done in https://github.com/domaindrivendev/Swashbuckle/issues/562).

### CODE REVIEW

**Comment by arthurkrupa** [comment]
Do you plan on updating this PR?

**Comment by mbliesath** [comment]
Would be great to have this fix available.

**Comment by Malchia7** [comment]
would also appreciate this being available. having to keep a static swagger.json around to account for things like this isn't great when the whole advantage of swashbuckle is auto-gen'd api doc from code.

**Comment by domaindrivendev** [comment]
@rboada04 - happy to merge this, can you sync with latest and get the tests passing?

**Comment by domaindrivendev** [comment]
Closing in favor of #619

**Pull request closed without merging**
