### PR TITLE
Add swagger dotnet tool

### LINKED ISSUE #761: Can let Swashbuckle.AspNetCore.Cli be .NET Core tool?
.NET Core 2.1 add the tool for cli,  would we get the tool version of Swashbuckle.AspNetCore.Cli?

### PR DESCRIPTION
**Pull request by kant2002**
- Bump to netcoreapp2.1, since this is minimal version supported by .NET Tools
- Name command as swagger (just so package could be used both ways hopefully)

Building and packaging
```
dotnet pack -c release -o ../artifacts /p:VersionSuffix=dev
```
Not sure how to propely integrate into existing build

Testing locally.
```
dotnet tool install --add-source <path-to-artifacts>artifacts\  Swashbuckle.AspNetCore.Cli
```

Closes #761

More information:
- https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create
- https://github.com/dotnet/core/tree/master/samples/dotnetsay

### CODE REVIEW

**Comment by domaindrivendev** [comment]
Awesome - thankyou @kant2002

**Comment by domaindrivendev** [comment]
@kant2002 - is there any chance you could update the v5 readme?
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README-v5.md

**Comment by aleccaputo** [comment]
@domaindrivendev the docs for this look like it's on the git page but there hasn't been an rc/beta release to include this code. Any idea when that will be?

**Comment by kant2002** [comment]
@aleccaputo I'm not sure, but seems to be the direction for the tool would be use new .NET Core 3 way of generation open-api documents using [Microsoft.Extensions.ApiDescription.Server Nuget](https://www.nuget.org/packages/Microsoft.Extensions.ApiDescription.Server/) which will provide shared infrastructure for generation of OpenAPI documents on build.

For you would be better manually generate Nuget package and place it in your custom nuget feed. I plac e build by me version to https://www.myget.org/feed/Packages/netcore-migration but seems to be that I now have to research new way of generation API based on way which MS will recommend soon.

**Comment by aleccaputo** [comment]
@kant2002 awesome thank you for the help, I'll look into that!

**Pull request merged**
