### PR TITLE
Support oneOf, allOf & discriminator for polymorphic hierarchies

### PR DESCRIPTION
**Pull request by domaindrivendev**

### CODE REVIEW

**Comment by the-vampiire** [comment]
can you point me where in the docs it describes how to use oneOf / allOf? i see this support was merged into master but cant find it in the docs

**Comment by AdamDiament** [comment]
> can you point me where in the docs it describes how to use oneOf / allOf? i see this support was merged into master but cant find it in the docs

The method swaggerGenOptions.GeneratePolymorphicSchemas in 5.4 1 appears to still only support oneOf - @domaindrivendev is there a way to get it to use all of?

**Comment by domaindrivendev** [comment]
The feature is still in an experimental phase hence why it’s not documented yet.

With that said it should already use oneOf when describing a base class (i.e. to list the known subtypes) and allOf when describing a subclass (i.e. to specify the base type).

Can you elaborate your use case please? What is your C# class hierarchy and how do you want it to be represented in Swagger using allOf?

**Comment by gpgpublickey** [comment]
Is this still experimental? @domaindrivendev could you please provide documentation ?

**Pull request merged**
