### PR TITLE
Add support for `JsonPolymorphic` and `JsonDerivedType` attributes to `Swashbuckle.AspNetCore.Annotations` for .NET7 and later

### LINKED ISSUE #2571: System.Text.JSON polymorphic behaviour not supported
Beginning with .NET 7, System.Text.Json supports polymorphic type hierarchy serialization and deserialization with attribute annotations.

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism

But if we configure swagger to use polymorphism it does not add information about derived type to docs.

As I think, the problem is that [JsonDerivedType] adds implicit discriminator property which can be seen in json string only. 

So, it is interesting to know the plans for support of this feature in library.

### PR DESCRIPTION
**Pull request by schnerring**
[Beginning with .NET 7, System.Text.Json supports polymorphic type hierarchy serialization and deserialization with attribute annotations.](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0) 

This PR adds support for `JsonPolymorphic` and `JsonDerivedType` attributes to `Swashbuckle.AspNetCore.Annotations` for .NET 7 and later.

Fixes #2571

### CODE REVIEW

**Comment by schnerring** [comment]
To fix the appveyor build, tests should be upgraded to net7 first. See related PR: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2672

**Comment by tomohisa** [comment]
This change would be great! @schnerring 
Looking forward to use it in Swashbuckle.AspNetCore.Annotations

**Comment by martincostello** [comment]
Thanks for contributing - if you'd like to continue with this pull request, please rebase against the default branch to pick up our new CI. We'd also need tests for these new scenarios.

**Comment by schnerring** [comment]
I rebased the PR against the current master branch.

The "test" (more of a sample) of the obsolete functionality is in here:

[test/WebSites/NswagClientExample/Controllers/AnimalsController.cs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2671/files#diff-baa567c0a93bd9c47b682852f77afb0937fa1063e292972b5d3a72583b31157f)

I've adjusted this to also include the new attributes.

Integration tests would be nice, but I don't know how to do that.

**Comment by martincostello** [comment]
> Integration tests would be nice, but I'm not sure how to do that from scratch and would appreciate some input. We basically need to test if the OpenAPI spec is generated correctly. Is there a test harness inside the code base I could reuse?

If you look at the [Swashbuckle.AspNetCore.IntegrationTests](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/Swashbuckle.AspNetCore.IntegrationTests) project, it validates things through the sites in the [WebSites](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/WebSites) folder. There are also verification tests associated with generated schemas [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/Swashbuckle.AspNetCore.SwaggerGen.Test/SwaggerGeneratorVerifyTests).

**Comment by ferhatmacak** [comment]
any progress?

**Comment by wont-work** [comment]
to anyone interested, it's possible to "manually" do what this PR does on your own code, until it gets merged: https://codeberg.org/KittyShopper/outpost/src/commit/3d8f0af997d3963ba552efe7ef9aec9b81d61a05/Outpost/Core/Util/OpenApi.cs#L135-L155

**Comment by martincostello** [comment]
The preferred approach is to add a controller/endpoint to one of the [test websites](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/WebSites) and then add appropriate verification tests to the [integration test](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/Swashbuckle.AspNetCore.IntegrationTests) project to verify that the expected OpenAPI document is produced. There's various examples of that approach [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerIntegrationTests.cs).

**Comment by schnerring** [comment]
Sorry @martincostello, I didn't want you to have to repeat yourself. You already told me earlier where to find the integration tests. But as far as I can tell, the old polymorphism feature is also untested, so there is no way for me to copy any tests and work from there. I also added a test case for the `NSwagClientExample` to test if a valid Swagger doc is generated, but I have given up after an hour of debugging.

However, I implemented your other code review suggestions. So maybe someone with more Swashbuckle expertise can pick up this PR in the future.

**Comment by Laurianti** [comment]
> to anyone interested, it's possible to "manually" do what this PR does on your own code, until it gets merged: https://codeberg.org/KittyShopper/outpost/src/commit/3d8f0af997d3963ba552efe7ef9aec9b81d61a05/Outpost/Core/Util/OpenApi.cs#L135-L155

Yes, it works, could you fix and merge the PR please?

**Comment by martincostello** [comment]
Superseded by #3170.

**Pull request closed without merging**
