### PR TITLE
Update swagger-ui-dist to 3.52.0

### LINKED ISSUE #2185: SecurityScheme Description not showing
When adding a Description to a SecurityScheme, it should be displayed in the authentication popup.

```csharp
SwaggerGenOptions.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
{
    Type = SecuritySchemeType.OAuth2,
    Flows = new OpenApiOAuthFlows
    {
        AuthorizationCode = new OpenApiOAuthFlow
        {
            AuthorizationUrl = new Uri("https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize"),
            TokenUrl = new Uri("https://login.microsoftonline.com/organizations/oauth2/v2.0/token"),
            Scopes = new Dictionary<string, string>
            {
                { $"api://{_config["AzureAd:ClientId"]}/user_impersonation", "Access API" }
            },

        }
    },
    Description = "`Leave client_secret blank`",
});
```

However, where I would expect the description to show up, the OAuthAppName is used instead.

image

Even if I remove the call to `SwaggerUIOptions.OAuthAppName("API")`, the description is still not shown.

Using the latest Swashbuckle 6.1.5.

### PR DESCRIPTION
**Pull request by h3rmanj**
Fixes #2185

### CODE REVIEW

**Comment by h3rmanj** [comment]
Not sure why the build fails, as the only thing changed is the package.json and package-lock.json

**Comment by domaindrivendev** [comment]
Might be resolved by https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2187. @h3rmanj can you try rebasing/merging master?

**Comment by h3rmanj** [comment]
Yep, that did the trick, thanks!

**Comment by h3rmanj** [comment]
@domaindrivendev any chance for a release?

**Pull request merged**
