### PR TITLE
Convert to msbuild

### PR DESCRIPTION
**Pull request by domaindrivendev**

### CODE REVIEW

**Comment by domaindrivendev** [comment]
Addresses #335

**Comment by domaindrivendev** [comment]
Closing in favor of 2c3e02334efe3d27c8118ff2afd7708443eee192

**Comment by mkontula** [comment]
In 2c3e023 core library references point to 1.0.* versions. Ruant's comment and commit in issue #335 addresses new packages. RC4 targeting current package versions would be greatly appreciated.

**Comment by domaindrivendev** [comment]
@mkontula - perhaps I'm missing something with the new csproj semantics but it's my understanding that the following ref ...

    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="1.0.0" />

specifies a dependency supporting any version of Core >= 1.0.0. In fact the docs [here](https://github.com/NuGet/Home/wiki/PackageReference-Specification) say exactly that:

_This means the same as 3.6.0 in project.json today, which is >=3.6.0, preferring the lowest_

As per the [Nuget best practices for package developers](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions), which states ...

_Developers most commonly specify a minimum version, which is a version number without adornmants as shown above, like 6.1.0. This allows NuGet to install that version or later_

I want to depend on a minimum version so that consumers can upgrade at their own pace.

At least that's my current understanding of things and what I consider to be best practice. @rynowak - if you have any input here it would be much appreciated (as always)?

**Comment by mkontula** [comment]
In a comment in #143 I found problems with rc3 when targeting net452. 

In my test project there's a reference to Microsoft.AspNetCore.Hosting.Abstractions. VS2017 shows, that version 1.1.1 is referenced. My API project references rc3 of this library. When the testhost builds starts the API project, this library is unhappy when it founds 1.1.1.0 and not 1.0.0.0 which gets referenced because rc3 references 1.0.0 of Microsoft.AspNetCore.Mvc.Core. 

I tried to bump versions of this libary up like @ruantt did as well, and the test project compiles & runs tests with no problem. Hopefully somebody with more understanding of this could help. Curiously enough, when I target netcoreapp1.1 with the API & Test project, no problems exists at all.

**Comment by ruant** [comment]
@mkontula I would love if someone could clarify how this should work as well.
What I did was a more try and fail approach 😆 until it worked.

I do agree with you, @domaindrivendev , it should depend on the minimum version it works with.

**Comment by mkontula** [comment]
I kind of repeated your work today @ruant and figured out these things: 
- running against full .net framework (in my case net452) assembly binding is different from netcoreapp1.1
- with net452 any reference which points to NET Core 1.0.* fails if the running environment (in my case xunit test project targeting net452) has references to 1.1.* packages.
- since SwashBuckle.AspNetCore.SwaggerGen references Microsoft.AspNetCore.Mvc.Core 1.0.0 it also wants the .NET Core packages with assembly version 1.0.0.0 when it's run against full framework. In my case the .NET Core packages were all from 1.1.* era and xunit was very unhappy like the snippet shows in #143.

This is more than weird and I'll raise a question in aspnetcore repo. If it won't be fixed, it should certainly be more clearly documented. As a workaround I bumped all versions up to current and stashed the binaries to our own myget feed.  Not pretty but it works.

**Pull request closed without merging**
