### PR TITLE
Added Nullable support for Schema Properties

### PR DESCRIPTION
**Pull request by vankooch**
Minor change to set nullable option in ```OpenApiSchema``` according to [Data-Types Specs](https://swagger.io/docs/specification/data-models/data-types/). This feature is particularly useful when used in combination with any code generators. I've also added a unit test.

### CODE REVIEW

**Comment by vankooch** [comment]
I've also update ReDoc to version 2.0.0-alpha.41 which has support for OpenAPI 3.
You can try all changes in this [MyGet Feed](https://www.myget.org/feed/Packages/kiarash-dev)

**Comment by vankooch** [comment]
Any chance that this will be merged soon?

Best regards

**Comment by domaindrivendev** [comment]
Agreed this would be a useful addition. The schema gen has just undergone a major refactor though - would you have time to rebase and implement against the latest version?

**Comment by vankooch** [comment]
Hi,
sorry for the late response, I was on holiday. I'll rebase and add the changes this week and send you an update.

**Comment by vankooch** [comment]
I've created a new PR #1051

**Pull request closed without merging**
