### PR TITLE
Allow no match to be found to avoid throwing an exception

### LINKED ISSUE #3187: [Bug]: Sequence contains no matching element when accessing swagger.json
### Describe the bug

The changes in #3133 made swagger.json crash with an InvalidOperationException when I try to access swagger.json in one of our services.

This is due to the code:
```C#
bodyParameterDescription = apiDescription.ParameterDescriptions.Single(desc => desc.IsFromBody());
if (bodyParameterDescription is not null)
```

Since this is using `.Single()`, `bodyParameterDescription` would never be null, so it seems that this was intended to use `SingleOrDefault` instead.

### Expected behavior

No crash on accessing swagger.json

### Actual behavior

Crash on accessing swagger.json

### Steps to reproduce

_No response_

### Exception(s) (if any)

Sequence contains no matching element
System.InvalidOperationException
  at System.Linq.ThrowHelper.ThrowNoMatchException()
  at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOpenApiOperationFromMetadataAsync(ApiDescription apiDescription, SchemaRepository schemaRepository)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository, Func`3 parametersGenerator, Func`3 bodyGenerator, Func`3 applyFilters)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationsAsync(IEnumerable\u00601 apiDescriptions, SchemaRepository schemaRepository)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository, Func`3 operationsGenerator)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
  at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
  at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

### Swashbuckle.AspNetCore version

7.1.0

### .NET Version

8.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by moni-dips**
# Pull Request

## The issue or feature being addressed

This change fixes #3187

## Details on the issue fix or feature implementation

The if indicates this was the intended method call to use.

### CODE REVIEW

**Comment by martincostello** [comment]
Thanks for the PR - could you update our tests to catch this issue so it doesn't regress in the future please.

**Comment by moni-dips** [comment]
I can do that, yes, but it will be some time before I can start looking at it.

**Comment by moni-dips** [comment]
> Thanks for the PR - could you update our tests to catch this issue so it doesn't regress in the future please.

Test has been added

**Review by martincostello — APPROVED** [review]

**Comment by martincostello** [comment]
Thanks for adding the test.

**Pull request merged**
