### PR TITLE
Target net5.0 explicitly for all projects

### PR DESCRIPTION
**Pull request by domaindrivendev**
Addresses #1998

### CODE REVIEW

**Comment by alexrosenfeld10** [comment]
Thanks for writing this up, I'll pull it down and try it out when it's released.

**Review by alexrosenfeld10 — APPROVED** [review]
Looks great, thank you for addressing this!

**Comment by alexrosenfeld10** [comment]
I noticed this got merged, @domaindrivendev any idea when I can expect the 6.0.4 build to come out?

**Comment by domaindrivendev** [comment]
I’ll push this tomorrow

**Pull request merged**
